### PR TITLE
Automated build2

### PR DESCRIPTION
**Pull request by nefarius2001**
Do you understand whats wrong here?

### CODE REVIEW

**Comment by ann0see** [comment]
Puh. I didn't get that you opened this PR to my repo.

I cdon't understand it yet, but you must keep in mind that the windows build depends on the content of the improve_win_ci branch

**Comment by nefarius2001** [comment]
does the request point to the newest commit of my branch(732f984)?

**Comment by ann0see** [comment]
I think so. Can you merge the content of my repo (enableWinBuild branch) in a branch on your repo, and merge the new windows installer (improve_win_ci branch on corrados repo)? This might allow you to have a working build for Windows and android

**Comment by ann0see** [comment]
I am 99% sure that this will work once https://github.com/corrados/jamulus/pull/841 is merged

**Comment by ann0see** [comment]
Can you merge corrados/master into your branch now?

**Comment by ann0see** [comment]
Let's have a look at it. I will merge it into a branch which is up to date with the current corrados master

**Comment by ann0see** [comment]
I think it works now?

**Pull request merged**
